sudo: false
language: python
matrix:
  include:
  - os: linux
    python: "3.5"
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
    env: PYTHON=3.5
  - os: linux
    python: "3.6"
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
    env: PYTHON=3.6

before_install:
  - pip$PY install --upgrade pip setuptools wheel

install:
  - if [ "${PYTHON:0:1}" = "3" ]; then export PY=3; fi
  - pip$PY install -r requirements.txt
  - pip$PY install pytest
  - pip$PY install pytest-cov
  - pip$PY install flake8
  - pip$PY install pylint
  - pip$PY install coveralls
  - python setup.py develop

script:
  - pytest ml/ --cov ml
  - flake8 --ignore=C408,E121,E123,E126,E226,E24,E704,W503,W504
after_success:
  - coveralls
