sudo: false
language: python
matrix:
  include:
  - os: linux
    python: "3.5"
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
    env: PYTHON=3.5
  - os: linux
    python: "3.6"
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
    env: PYTHON=3.6

before_install:
  - pip$PY install --upgrade pip setuptools wheel

install:
  - if [ "${PYTHON:0:1}" = "3" ]; then export PY=3; fi
  - pip$PY install -r requirements.txt
  - pip$PY install pytest
  - pip$PY install pytest-cov
  - pip$PY install coveralls

script: pytest ml/ --cov ml

after_success:
- coveralls